//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ui.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RaceTranslations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RaceTranslations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ui.Translations.RaceTranslations", typeof(RaceTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DarkElves {
            get {
                return ResourceManager.GetString("DarkElves", resourceCulture);
            }
        }
        
        public static string DE_Assassine {
            get {
                return ResourceManager.GetString("DE_Assassine", resourceCulture);
            }
        }
        
        public static string DE_Blitzer {
            get {
                return ResourceManager.GetString("DE_Blitzer", resourceCulture);
            }
        }
        
        public static string DE_LineMan {
            get {
                return ResourceManager.GetString("DE_LineMan", resourceCulture);
            }
        }
        
        public static string DE_WitchElve {
            get {
                return ResourceManager.GetString("DE_WitchElve", resourceCulture);
            }
        }
        
        public static string Dwarfs {
            get {
                return ResourceManager.GetString("Dwarfs", resourceCulture);
            }
        }
        
        public static string DW_Blitzer {
            get {
                return ResourceManager.GetString("DW_Blitzer", resourceCulture);
            }
        }
        
        public static string DW_Blocker {
            get {
                return ResourceManager.GetString("DW_Blocker", resourceCulture);
            }
        }
        
        public static string DW_DeathRoller {
            get {
                return ResourceManager.GetString("DW_DeathRoller", resourceCulture);
            }
        }
        
        public static string DW_Runner {
            get {
                return ResourceManager.GetString("DW_Runner", resourceCulture);
            }
        }
        
        public static string DW_TrollSlayer {
            get {
                return ResourceManager.GetString("DW_TrollSlayer", resourceCulture);
            }
        }
        
        public static string Humans {
            get {
                return ResourceManager.GetString("Humans", resourceCulture);
            }
        }
        
        public static string HU_Blitzer {
            get {
                return ResourceManager.GetString("HU_Blitzer", resourceCulture);
            }
        }
        
        public static string HU_Catcher {
            get {
                return ResourceManager.GetString("HU_Catcher", resourceCulture);
            }
        }
        
        public static string HU_LineMan {
            get {
                return ResourceManager.GetString("HU_LineMan", resourceCulture);
            }
        }
        
        public static string HU_Ogre {
            get {
                return ResourceManager.GetString("HU_Ogre", resourceCulture);
            }
        }
        
        public static string HU_Thrower {
            get {
                return ResourceManager.GetString("HU_Thrower", resourceCulture);
            }
        }
        
        public static string NominatedMostValuablePlayer {
            get {
                return ResourceManager.GetString("NominatedMostValuablePlayer", resourceCulture);
            }
        }
        
        public static string PlayerPassed {
            get {
                return ResourceManager.GetString("PlayerPassed", resourceCulture);
            }
        }
        
        public static string PlayerMadeCasualty {
            get {
                return ResourceManager.GetString("PlayerMadeCasualty", resourceCulture);
            }
        }
        
        public static string PlayerMadeTouchdown {
            get {
                return ResourceManager.GetString("PlayerMadeTouchdown", resourceCulture);
            }
        }
    }
}
