//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ui.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RaceTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RaceTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ui.Translations.RaceTranslations", typeof(RaceTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Elves.
        /// </summary>
        public static string DarkElves {
            get {
                return ResourceManager.GetString("DarkElves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assasine.
        /// </summary>
        public static string DE_Assassine {
            get {
                return ResourceManager.GetString("DE_Assassine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitzer.
        /// </summary>
        public static string DE_Blitzer {
            get {
                return ResourceManager.GetString("DE_Blitzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineman.
        /// </summary>
        public static string DE_LineMan {
            get {
                return ResourceManager.GetString("DE_LineMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witchelve.
        /// </summary>
        public static string DE_WitchElve {
            get {
                return ResourceManager.GetString("DE_WitchElve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitzer.
        /// </summary>
        public static string DW_Blitzer {
            get {
                return ResourceManager.GetString("DW_Blitzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocker.
        /// </summary>
        public static string DW_Blocker {
            get {
                return ResourceManager.GetString("DW_Blocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Roller.
        /// </summary>
        public static string DW_DeathRoller {
            get {
                return ResourceManager.GetString("DW_DeathRoller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner.
        /// </summary>
        public static string DW_Runner {
            get {
                return ResourceManager.GetString("DW_Runner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troll Slayer.
        /// </summary>
        public static string DW_TrollSlayer {
            get {
                return ResourceManager.GetString("DW_TrollSlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarfs.
        /// </summary>
        public static string Dwarfs {
            get {
                return ResourceManager.GetString("Dwarfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitzer.
        /// </summary>
        public static string HU_Blitzer {
            get {
                return ResourceManager.GetString("HU_Blitzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catcher.
        /// </summary>
        public static string HU_Catcher {
            get {
                return ResourceManager.GetString("HU_Catcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineman.
        /// </summary>
        public static string HU_LineMan {
            get {
                return ResourceManager.GetString("HU_LineMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogre.
        /// </summary>
        public static string HU_Ogre {
            get {
                return ResourceManager.GetString("HU_Ogre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrower.
        /// </summary>
        public static string HU_Thrower {
            get {
                return ResourceManager.GetString("HU_Thrower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humans.
        /// </summary>
        public static string Humans {
            get {
                return ResourceManager.GetString("Humans", resourceCulture);
            }
        }
    }
}
